### ISSUE TITLE
Gravity not working

### ISSUE THREAD

**Issue by MagpieTear** [RypoFalem/ArmorStandEditor#20] opened 2019-10-19 19:05 UTC
Multiple users on a paper server experiencing an issue where gravity is always off, regardless of what the display states.

**Comment by RoboMWM** [comment] 2019-10-20 00:46
Did you disable armor stand ticking in paper config?

**Comment by RypoFalem** [comment] 2019-10-22 03:20
I can't reproduce in the latest version of paper

**Comment by RypoFalem** [comment] 2019-10-25 05:25
Gonna assume it was just an issue with the server software that's now fixed. Lemme know if this isn't the case!

**Closed as completed by RypoFalem** 2019-10-25 05:25 UTC
